// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: Lexer.flex

package analizadores;
import java_cup.runtime.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\1"+
    "\1\5\1\6\1\0\1\7\1\10\1\11\1\0\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\7\23\2\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\0\3\33\1\34\1\35\1\34\2\7\1\36\2\7"+
    "\1\37\6\7\1\40\4\7\1\41\2\7\1\42\1\0"+
    "\1\43\1\44\1\7\1\0\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\1\63\1\64\1\7\1\65\1\66\1\67"+
    "\1\70\1\71\1\72\1\73\1\74\1\75\1\76\1\77"+
    "\1\100\1\101\6\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\2\20\1\21\1\22\1\23\1\24\1\25\1\1\1\5"+
    "\1\26\1\27\1\30\23\5\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\2\0\1\2\1\47\1\20\1\0\1\46"+
    "\1\0\1\20\1\0\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\3\5\1\56\12\5\1\57\7\5\1\60\1\5"+
    "\1\61\25\5\1\62\1\63\1\64\4\2\1\0\1\46"+
    "\1\20\1\65\1\66\1\67\25\5\1\70\1\5\1\71"+
    "\4\5\1\61\32\5\1\72\1\73\5\5\1\74\7\5"+
    "\1\75\20\5\1\76\5\5\1\77\1\100\4\5\1\101"+
    "\1\102\1\103\13\5\1\104\4\5\1\61\2\5\1\105"+
    "\1\106\4\5\1\107\2\5\1\110\4\5\1\111\1\112"+
    "\1\5\1\113\3\5\1\114\1\5\1\115\2\5\1\116"+
    "\1\117\3\5\1\120\3\5\1\121\2\5";

  private static int [] zzUnpackAction() {
    int [] result = new int[296];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\102\0\102\0\204\0\306\0\102\0\u0108\0\u014a"+
    "\0\u018c\0\102\0\102\0\u01ce\0\u0210\0\102\0\u0252\0\u0294"+
    "\0\u02d6\0\u0318\0\u035a\0\102\0\102\0\u039c\0\u03de\0\u0420"+
    "\0\u0462\0\u04a4\0\102\0\102\0\u04e6\0\u0528\0\u056a\0\u05ac"+
    "\0\u05ee\0\u0630\0\u0672\0\u06b4\0\u06f6\0\u0738\0\u077a\0\u07bc"+
    "\0\u07fe\0\u0840\0\u0882\0\u08c4\0\u0906\0\u0948\0\u098a\0\u09cc"+
    "\0\102\0\u0a0e\0\102\0\u0a50\0\102\0\102\0\102\0\102"+
    "\0\102\0\102\0\102\0\102\0\102\0\u0a92\0\u0ad4\0\u0b16"+
    "\0\u0b58\0\u0ad4\0\u0b9a\0\u0bdc\0\102\0\u0c1e\0\102\0\u0c60"+
    "\0\u0ca2\0\102\0\102\0\102\0\u0ce4\0\102\0\u0d26\0\u0d68"+
    "\0\u0daa\0\102\0\u0dec\0\u0e2e\0\u0e70\0\u0eb2\0\u0ef4\0\u0f36"+
    "\0\u0f78\0\u0fba\0\u0ffc\0\u103e\0\u1080\0\u10c2\0\u1104\0\u1146"+
    "\0\u1188\0\u11ca\0\u120c\0\u124e\0\u0108\0\u1290\0\u12d2\0\u1314"+
    "\0\u1356\0\u1398\0\u13da\0\u141c\0\u145e\0\u14a0\0\u14e2\0\u1524"+
    "\0\u1566\0\u15a8\0\u15ea\0\u162c\0\u166e\0\u16b0\0\u16f2\0\u1734"+
    "\0\u1776\0\u17b8\0\u17fa\0\u183c\0\102\0\102\0\102\0\u187e"+
    "\0\u0ad4\0\u18c0\0\u1902\0\u1944\0\u1986\0\u19c8\0\102\0\102"+
    "\0\102\0\u1a0a\0\u1a4c\0\u1a8e\0\u1ad0\0\u1b12\0\u1b54\0\u1b96"+
    "\0\u1bd8\0\u1c1a\0\u1c5c\0\u1c9e\0\u1ce0\0\u1d22\0\u1d64\0\u1da6"+
    "\0\u1de8\0\u1e2a\0\u1e6c\0\u1eae\0\u1ef0\0\u1f32\0\u0108\0\u1f74"+
    "\0\u1fb6\0\u1ff8\0\u203a\0\u207c\0\u20be\0\u0108\0\u2100\0\u2142"+
    "\0\u2184\0\u21c6\0\u2208\0\u224a\0\u228c\0\u22ce\0\u2310\0\u2352"+
    "\0\u2394\0\u23d6\0\u2418\0\u245a\0\u249c\0\u24de\0\u2520\0\u2562"+
    "\0\u25a4\0\u25e6\0\u2628\0\u266a\0\u26ac\0\u26ee\0\u2730\0\u2772"+
    "\0\u0108\0\u0108\0\u27b4\0\u27f6\0\u2838\0\u287a\0\u28bc\0\u0108"+
    "\0\u28fe\0\u2940\0\u2982\0\u29c4\0\u2a06\0\u2a48\0\u2a8a\0\u0108"+
    "\0\u2acc\0\u2b0e\0\u2b50\0\u2b92\0\u2bd4\0\u2c16\0\u2c58\0\u2c9a"+
    "\0\u2cdc\0\u2d1e\0\u2d60\0\u2da2\0\u2de4\0\u2e26\0\u2e68\0\u2eaa"+
    "\0\u0108\0\u2eec\0\u2f2e\0\u2f70\0\u2fb2\0\u2ff4\0\u0108\0\u0108"+
    "\0\u3036\0\u3078\0\u30ba\0\u30fc\0\u0108\0\u313e\0\u0108\0\u3180"+
    "\0\u31c2\0\u3204\0\u3246\0\u3288\0\u32ca\0\u330c\0\u334e\0\u3390"+
    "\0\u33d2\0\u3414\0\u0108\0\u3456\0\u3498\0\u34da\0\u351c\0\u1b12"+
    "\0\u355e\0\u35a0\0\u0108\0\u0108\0\u35e2\0\u3624\0\u3666\0\u36a8"+
    "\0\u0108\0\u36ea\0\u372c\0\u0108\0\u376e\0\u37b0\0\u37f2\0\u3834"+
    "\0\u0108\0\u0108\0\u3876\0\u0108\0\u38b8\0\u38fa\0\u393c\0\u0108"+
    "\0\u397e\0\u0108\0\u39c0\0\u3a02\0\u0108\0\u0108\0\u3a44\0\u3a86"+
    "\0\u3ac8\0\u0108\0\u3b0a\0\u3b4c\0\u3b8e\0\u0108\0\u3bd0\0\u3c12";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[296];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\2\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\5\7\1\32\1\7\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\2\7\1\44\1\45"+
    "\1\7\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\56\1\57\1\60\3\7\1\61\1\62\1\63"+
    "\1\64\104\0\1\3\127\0\1\65\60\0\1\7\12\0"+
    "\3\7\6\0\7\7\3\0\31\7\34\0\1\66\62\0"+
    "\1\67\16\0\1\70\101\0\1\71\66\0\1\72\12\0"+
    "\1\73\70\0\1\74\10\0\1\75\73\0\3\76\55\0"+
    "\14\77\1\100\4\77\1\101\6\77\1\102\51\77\20\0"+
    "\1\76\1\0\2\103\1\104\7\0\1\105\1\106\1\0"+
    "\1\107\1\0\1\110\6\0\1\105\1\106\1\105\5\0"+
    "\1\107\12\0\1\110\26\0\1\76\1\0\3\23\7\0"+
    "\1\105\1\106\1\0\1\107\10\0\1\105\1\106\1\105"+
    "\5\0\1\107\50\0\1\111\1\112\101\0\1\113\101\0"+
    "\1\114\1\115\75\0\1\116\63\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\2\7\1\117\17\7\1\120\4\7"+
    "\1\121\1\7\34\0\1\122\60\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\1\7\1\123\16\7\1\124\1\125"+
    "\7\7\13\0\1\7\12\0\3\7\6\0\7\7\3\0"+
    "\16\7\1\126\1\7\1\127\6\7\1\130\1\7\13\0"+
    "\1\7\12\0\3\7\6\0\7\7\3\0\1\131\12\7"+
    "\1\132\2\7\1\133\12\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\4\7\1\134\11\7\1\135\12\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\13\7"+
    "\1\136\1\7\1\137\10\7\1\140\2\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\1\141\7\7\1\142"+
    "\2\7\1\143\2\7\1\144\12\7\13\0\1\7\12\0"+
    "\3\7\6\0\7\7\3\0\5\7\1\145\6\7\1\146"+
    "\1\147\13\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\1\150\30\7\13\0\1\7\12\0\3\7\6\0"+
    "\7\7\3\0\16\7\1\151\12\7\13\0\1\7\12\0"+
    "\3\7\6\0\7\7\3\0\1\152\30\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\1\153\3\7\1\154"+
    "\16\7\1\155\5\7\13\0\1\7\12\0\3\7\6\0"+
    "\7\7\3\0\23\7\1\156\5\7\13\0\1\7\12\0"+
    "\3\7\6\0\7\7\3\0\1\157\17\7\1\160\2\7"+
    "\1\161\5\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\4\7\1\162\24\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\7\7\1\163\12\7\1\164\1\165"+
    "\1\7\1\166\1\7\1\167\1\7\13\0\1\7\12\0"+
    "\3\7\6\0\7\7\3\0\7\7\1\170\10\7\1\171"+
    "\10\7\13\0\1\7\12\0\3\7\6\0\7\7\3\0"+
    "\22\7\1\172\6\7\13\0\1\7\12\0\3\7\6\0"+
    "\7\7\3\0\16\7\1\173\12\7\13\0\1\7\12\0"+
    "\3\7\6\0\7\7\3\0\7\7\1\174\21\7\34\0"+
    "\1\175\46\0\1\176\32\0\1\177\73\0\3\76\7\0"+
    "\1\105\1\106\12\0\1\105\1\106\1\105\27\0\21\77"+
    "\1\3\101\77\1\200\60\77\2\101\1\201\1\101\1\202"+
    "\14\101\1\203\60\101\20\0\1\76\1\0\2\103\1\104"+
    "\7\0\1\105\1\106\1\0\1\107\10\0\1\105\1\106"+
    "\1\105\5\0\1\107\41\0\1\76\1\0\3\104\7\0"+
    "\1\105\1\106\12\0\1\105\1\106\1\105\44\0\1\204"+
    "\1\0\1\204\2\0\3\205\77\0\3\206\6\0\3\206"+
    "\7\0\6\206\57\0\1\207\101\0\1\210\1\211\57\0"+
    "\1\7\12\0\3\7\6\0\7\7\3\0\1\212\30\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\20\7"+
    "\1\213\10\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\21\7\1\214\7\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\21\7\1\215\7\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\6\7\1\216\22\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\21\7"+
    "\1\217\7\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\16\7\1\220\12\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\4\7\1\221\24\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\22\7\1\222\6\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\21\7"+
    "\1\223\1\224\6\7\13\0\1\7\12\0\3\7\6\0"+
    "\7\7\3\0\1\225\30\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\15\7\1\226\13\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\5\7\1\227\23\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\23\7"+
    "\1\230\5\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\21\7\1\231\7\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\23\7\1\232\5\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\22\7\1\233\6\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\13\7"+
    "\1\234\15\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\15\7\1\235\13\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\16\7\1\236\12\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\20\7\1\237\10\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\17\7"+
    "\1\240\11\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\22\7\1\241\6\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\24\7\1\242\4\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\15\7\1\243\13\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\10\7"+
    "\1\244\20\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\22\7\1\245\6\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\25\7\1\246\1\247\2\7\13\0"+
    "\1\7\12\0\3\7\6\0\7\7\3\0\13\7\1\250"+
    "\15\7\13\0\1\7\12\0\3\7\6\0\7\7\3\0"+
    "\22\7\1\246\6\7\13\0\1\7\12\0\3\7\6\0"+
    "\7\7\3\0\2\7\1\251\26\7\13\0\1\7\12\0"+
    "\3\7\6\0\7\7\3\0\10\7\1\252\5\7\1\253"+
    "\12\7\13\0\1\7\12\0\3\7\6\0\7\7\3\0"+
    "\1\7\1\254\27\7\13\0\1\7\12\0\3\7\6\0"+
    "\7\7\3\0\22\7\1\255\6\7\13\0\1\7\12\0"+
    "\3\7\6\0\7\7\3\0\16\7\1\256\12\7\13\0"+
    "\1\7\12\0\3\7\6\0\7\7\3\0\1\257\17\7"+
    "\1\260\10\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\17\7\1\261\11\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\10\7\1\262\20\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\15\7\1\263\13\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\10\7"+
    "\1\216\7\7\1\264\10\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\1\265\22\7\1\266\3\7\1\246"+
    "\1\7\13\0\1\7\12\0\3\7\6\0\7\7\3\0"+
    "\10\7\1\250\20\7\13\0\1\7\12\0\3\7\6\0"+
    "\7\7\3\0\10\7\1\267\2\7\1\270\15\7\13\0"+
    "\1\7\12\0\3\7\6\0\7\7\3\0\10\7\1\271"+
    "\20\7\25\0\1\3\60\0\2\77\1\201\16\77\1\3"+
    "\60\77\2\203\1\3\1\203\1\4\75\203\22\0\3\205"+
    "\77\0\3\205\7\0\1\105\13\0\1\105\1\0\1\105"+
    "\51\0\3\206\6\0\3\206\1\0\1\107\5\0\6\206"+
    "\5\0\1\107\30\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\15\7\1\272\13\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\10\7\1\273\20\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\22\7\1\274\6\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\22\7"+
    "\1\275\6\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\21\7\1\246\7\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\4\7\1\276\24\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\13\7\1\277\15\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\1\300"+
    "\30\7\13\0\1\7\12\0\3\7\6\0\7\7\3\0"+
    "\4\7\1\301\24\7\13\0\1\7\12\0\3\7\6\0"+
    "\7\7\3\0\4\7\1\302\24\7\13\0\1\7\12\0"+
    "\3\7\6\0\7\7\3\0\2\7\1\303\26\7\13\0"+
    "\1\7\12\0\3\7\6\0\7\7\3\0\21\7\1\304"+
    "\7\7\13\0\1\7\12\0\3\7\6\0\7\7\3\0"+
    "\22\7\1\305\6\7\13\0\1\7\12\0\3\7\6\0"+
    "\7\7\3\0\1\306\30\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\1\7\1\307\27\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\4\7\1\310\24\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\14\7"+
    "\1\246\14\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\4\7\1\311\24\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\21\7\1\312\7\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\1\313\30\7\13\0"+
    "\1\7\12\0\3\7\6\0\7\7\3\0\1\314\30\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\13\7"+
    "\1\315\2\7\1\316\12\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\4\7\1\317\24\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\1\246\30\7\13\0"+
    "\1\7\12\0\3\7\6\0\7\7\3\0\6\7\1\320"+
    "\22\7\13\0\1\7\12\0\3\7\6\0\7\7\3\0"+
    "\15\7\1\246\13\7\13\0\1\7\12\0\3\7\6\0"+
    "\7\7\3\0\10\7\1\321\20\7\13\0\1\7\12\0"+
    "\3\7\6\0\7\7\3\0\22\7\1\322\6\7\13\0"+
    "\1\7\12\0\3\7\6\0\7\7\3\0\13\7\1\246"+
    "\15\7\13\0\1\7\12\0\3\7\6\0\7\7\3\0"+
    "\12\7\1\323\16\7\13\0\1\7\12\0\3\7\6\0"+
    "\7\7\3\0\15\7\1\324\6\7\1\325\4\7\13\0"+
    "\1\7\12\0\3\7\6\0\7\7\3\0\22\7\1\326"+
    "\6\7\13\0\1\7\12\0\3\7\6\0\7\7\3\0"+
    "\13\7\1\327\15\7\13\0\1\7\12\0\3\7\6\0"+
    "\7\7\3\0\23\7\1\330\5\7\13\0\1\7\12\0"+
    "\3\7\6\0\7\7\3\0\20\7\1\331\10\7\13\0"+
    "\1\7\12\0\3\7\6\0\7\7\3\0\22\7\1\332"+
    "\6\7\13\0\1\7\12\0\3\7\6\0\7\7\3\0"+
    "\10\7\1\333\20\7\13\0\1\7\12\0\3\7\6\0"+
    "\7\7\3\0\4\7\1\334\24\7\13\0\1\7\12\0"+
    "\3\7\6\0\7\7\3\0\22\7\1\335\6\7\13\0"+
    "\1\7\12\0\3\7\6\0\7\7\3\0\2\7\1\336"+
    "\26\7\13\0\1\7\12\0\3\7\6\0\7\7\3\0"+
    "\16\7\1\337\12\7\13\0\1\7\12\0\3\7\6\0"+
    "\7\7\3\0\15\7\1\340\13\7\13\0\1\7\12\0"+
    "\3\7\6\0\7\7\3\0\4\7\1\341\24\7\13\0"+
    "\1\7\12\0\3\7\6\0\7\7\3\0\3\7\1\246"+
    "\25\7\13\0\1\7\12\0\3\7\6\0\7\7\3\0"+
    "\1\342\30\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\13\7\1\343\15\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\15\7\1\261\13\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\15\7\1\344\13\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\4\7"+
    "\1\232\24\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\20\7\1\345\10\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\20\7\1\156\10\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\4\7\1\346\24\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\12\7"+
    "\1\347\16\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\7\7\1\246\21\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\21\7\1\350\7\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\10\7\1\351\20\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\23\7"+
    "\1\352\5\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\13\7\1\353\15\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\15\7\1\354\13\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\4\7\1\355\24\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\13\7"+
    "\1\356\15\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\22\7\1\357\6\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\4\7\1\360\24\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\20\7\1\361\10\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\20\7"+
    "\1\362\10\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\24\7\1\363\4\7\13\0\1\7\12\0\3\7"+
    "\6\0\3\7\1\364\3\7\3\0\31\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\1\365\30\7\13\0"+
    "\1\7\12\0\3\7\6\0\7\7\3\0\22\7\1\366"+
    "\6\7\13\0\1\7\12\0\3\7\6\0\7\7\3\0"+
    "\1\367\30\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\4\7\1\370\24\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\10\7\1\371\20\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\20\7\1\372\10\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\22\7"+
    "\1\373\6\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\10\7\1\374\20\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\2\7\1\375\26\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\20\7\1\246\10\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\2\7"+
    "\1\376\26\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\7\7\1\377\21\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\25\7\1\u0100\3\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\21\7\1\u0101\7\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\22\7"+
    "\1\u0102\6\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\4\7\1\u0103\24\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\6\7\1\u0104\22\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\1\u0105\30\7\13\0"+
    "\1\7\12\0\3\7\6\0\7\7\3\0\1\u0106\30\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\15\7"+
    "\1\u0107\13\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\13\7\1\u0108\15\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\4\7\1\u0109\24\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\3\7\1\216\25\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\13\7"+
    "\1\u010a\15\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\14\7\1\u010b\14\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\22\7\1\u010c\6\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\5\7\1\u010d\23\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\4\7"+
    "\1\246\24\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\15\7\1\156\13\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\6\7\1\u010e\22\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\13\7\1\244\15\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\22\7"+
    "\1\u010f\6\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\2\7\1\u0110\26\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\2\7\1\u0111\26\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\15\7\1\u0112\13\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\2\7"+
    "\1\246\26\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\22\7\1\u0113\6\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\7\7\1\u0114\21\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\20\7\1\u0115\10\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\10\7"+
    "\1\u0116\20\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\10\7\1\u0117\20\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\2\7\1\156\26\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\15\7\1\u0118\13\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\23\7"+
    "\1\u0119\5\7\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\22\7\1\u011a\6\7\13\0\1\7\12\0\3\7"+
    "\6\0\7\7\3\0\27\7\1\246\1\7\13\0\1\7"+
    "\12\0\3\7\6\0\7\7\3\0\4\7\1\u011b\24\7"+
    "\13\0\1\7\12\0\3\7\6\0\7\7\3\0\1\u011c"+
    "\30\7\13\0\1\7\12\0\3\7\6\0\7\7\3\0"+
    "\4\7\1\u011d\24\7\13\0\1\7\12\0\3\7\6\0"+
    "\7\7\3\0\4\7\1\u011e\24\7\13\0\1\7\12\0"+
    "\3\7\6\0\7\7\3\0\22\7\1\u011f\6\7\13\0"+
    "\1\7\12\0\3\7\6\0\7\7\3\0\5\7\1\u0120"+
    "\23\7\13\0\1\7\12\0\3\7\6\0\7\7\3\0"+
    "\16\7\1\u0121\12\7\13\0\1\7\12\0\3\7\6\0"+
    "\7\7\3\0\4\7\1\364\24\7\13\0\1\7\12\0"+
    "\3\7\6\0\7\7\3\0\13\7\1\363\15\7\13\0"+
    "\1\7\12\0\3\7\6\0\7\7\3\0\4\7\1\u0122"+
    "\24\7\13\0\1\7\12\0\3\7\6\0\7\7\3\0"+
    "\15\7\1\u0123\13\7\13\0\1\7\12\0\3\7\6\0"+
    "\7\7\3\0\2\7\1\363\26\7\13\0\1\7\12\0"+
    "\3\7\6\0\7\7\3\0\4\7\1\u0124\24\7\13\0"+
    "\1\7\12\0\3\7\6\0\7\7\3\0\17\7\1\246"+
    "\11\7\13\0\1\7\12\0\3\7\6\0\7\7\3\0"+
    "\15\7\1\u0125\13\7\13\0\1\7\12\0\3\7\6\0"+
    "\7\7\3\0\22\7\1\216\6\7\13\0\1\7\12\0"+
    "\3\7\6\0\7\7\3\0\3\7\1\u0126\25\7\13\0"+
    "\1\7\12\0\3\7\6\0\7\7\3\0\10\7\1\u0127"+
    "\20\7\13\0\1\7\12\0\3\7\6\0\7\7\3\0"+
    "\30\7\1\u0128\13\0\1\7\12\0\3\7\6\0\7\7"+
    "\3\0\4\7\1\267\24\7\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[15444];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\2\1\1\11\3\1\2\11\2\1\1\11"+
    "\5\1\2\11\5\1\2\11\24\1\1\11\1\1\1\11"+
    "\1\1\11\11\1\1\2\0\3\1\1\0\1\11\1\0"+
    "\1\11\1\0\1\1\3\11\1\1\1\11\3\1\1\11"+
    "\52\1\3\11\4\1\1\0\2\1\3\11\237\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[296];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol token(int id, int l, int r, String o){
        return new Symbol(id, l, r, o);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(sym.ERROR, yyline, yycolumn, yytext());
            }
            // fall through
          case 82: break;
          case 2:
            { 
            }
            // fall through
          case 83: break;
          case 3:
            { return token(sym.NEGACION, yyline, yycolumn, yytext());
            }
            // fall through
          case 84: break;
          case 4:
            { return token(sym.COMILLAS, yyline, yycolumn, yytext());
            }
            // fall through
          case 85: break;
          case 5:
            { return token(sym.IDENTIFICADOR, yyline, yycolumn, yytext());
            }
            // fall through
          case 86: break;
          case 6:
            { return token(sym.MODULO, yyline, yycolumn, yytext());
            }
            // fall through
          case 87: break;
          case 7:
            { return token(sym.AND, yyline, yycolumn, yytext());
            }
            // fall through
          case 88: break;
          case 8:
            { return token(sym.PARENTESISIZQ, yyline, yycolumn, yytext());
            }
            // fall through
          case 89: break;
          case 9:
            { return token(sym.PARENTESISDER, yyline, yycolumn, yytext());
            }
            // fall through
          case 90: break;
          case 10:
            { return token(sym.MULTIPLICACION, yyline, yycolumn, yytext());
            }
            // fall through
          case 91: break;
          case 11:
            { return token(sym.SUMA, yyline, yycolumn, yytext());
            }
            // fall through
          case 92: break;
          case 12:
            { return token(sym.COMA, yyline, yycolumn, yytext());
            }
            // fall through
          case 93: break;
          case 13:
            { return token(sym.RESTA, yyline, yycolumn, yytext());
            }
            // fall through
          case 94: break;
          case 14:
            { return token(sym.PUNTO, yyline, yycolumn, yytext());
            }
            // fall through
          case 95: break;
          case 15:
            { return token(sym.DIAGONAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 96: break;
          case 16:
            { return token(sym.ENTERO, yyline, yycolumn, yytext());
            }
            // fall through
          case 97: break;
          case 17:
            { return token(sym.DOSPUNTOS, yyline, yycolumn, yytext());
            }
            // fall through
          case 98: break;
          case 18:
            { return token(sym.PUNTOYCOMA, yyline, yycolumn, yytext());
            }
            // fall through
          case 99: break;
          case 19:
            { return token(sym.MENORQUE, yyline, yycolumn, yytext());
            }
            // fall through
          case 100: break;
          case 20:
            { return token(sym.ASIGNACION, yyline, yycolumn, yytext());
            }
            // fall through
          case 101: break;
          case 21:
            { return token(sym.MAYORQUE, yyline, yycolumn, yytext());
            }
            // fall through
          case 102: break;
          case 22:
            { return token(sym.CORCHETEIZQ, yyline, yycolumn, yytext());
            }
            // fall through
          case 103: break;
          case 23:
            { return token(sym.CORCHETEDER,  yyline, yycolumn, yytext());
            }
            // fall through
          case 104: break;
          case 24:
            { return token(sym.EXPONENTE, yyline, yycolumn, yytext());
            }
            // fall through
          case 105: break;
          case 25:
            { return token(sym.LLAVEIZQ, yyline, yycolumn, yytext());
            }
            // fall through
          case 106: break;
          case 26:
            { return token(sym.OR, yyline, yycolumn, yytext());
            }
            // fall through
          case 107: break;
          case 27:
            { return token(sym.LLAVEDER, yyline, yycolumn, yytext());
            }
            // fall through
          case 108: break;
          case 28:
            { return token(sym.VIRGUILLA, yyline, yycolumn, yytext());
            }
            // fall through
          case 109: break;
          case 29:
            { return token(sym.DIFERENTEDE, yyline, yycolumn, yytext());
            }
            // fall through
          case 110: break;
          case 30:
            { return token(sym.MODULOIGUAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 111: break;
          case 31:
            { return token(sym.ANDLOGICO, yyline, yycolumn, yytext());
            }
            // fall through
          case 112: break;
          case 32:
            { return token(sym.ANDIGUAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 113: break;
          case 33:
            { return token(sym.PORIGUAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 114: break;
          case 34:
            { return token(sym.INCREMENTO, yyline, yycolumn, yytext());
            }
            // fall through
          case 115: break;
          case 35:
            { return token(sym.MASIGUAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 116: break;
          case 36:
            { return token(sym.DECREMENTO, yyline, yycolumn, yytext());
            }
            // fall through
          case 117: break;
          case 37:
            { return token(sym.MENOSIGUAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 118: break;
          case 38:
            { return token(sym.FLOTANTE, yyline, yycolumn, yytext());
            }
            // fall through
          case 119: break;
          case 39:
            { return token(sym.DIVISIONIGUAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 120: break;
          case 40:
            { return token(sym.DOBLEMAYORQUE, yyline, yycolumn, yytext());
            }
            // fall through
          case 121: break;
          case 41:
            { return token(sym.MENORIGUAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 122: break;
          case 42:
            { return token(sym.IGUAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 123: break;
          case 43:
            { return token(sym.MAYORIGUAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 124: break;
          case 44:
            { return token(sym.DOBLEMENORQUE, yyline, yycolumn, yytext());
            }
            // fall through
          case 125: break;
          case 45:
            { return token(sym.INTERROGACION, yyline, yycolumn, yytext());
            }
            // fall through
          case 126: break;
          case 46:
            { return token(sym.ASIGNACIONOREXCLUSIVO, yyline, yycolumn, yytext());
            }
            // fall through
          case 127: break;
          case 47:
            { return token(sym.DO, yyline, yycolumn, yytext());
            }
            // fall through
          case 128: break;
          case 48:
            { return token(sym.IF, yyline, yycolumn, yytext());
            }
            // fall through
          case 129: break;
          case 49:
            { return token(sym.RESERVADA, yyline, yycolumn, yytext());
            }
            // fall through
          case 130: break;
          case 50:
            { return token(sym.ORIGUAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 131: break;
          case 51:
            { return token(sym.ORLOGICO, yyline, yycolumn, yytext());
            }
            // fall through
          case 132: break;
          case 52:
            { return token(sym.NOTIGUAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 133: break;
          case 53:
            { return token(sym.DOBLEMAYORQUEIGUAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 134: break;
          case 54:
            { return token(sym.DOBLEMENORQUEIGUAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 135: break;
          case 55:
            { return token(sym.TRIPLEMENORQUE, yyline, yycolumn, yytext());
            }
            // fall through
          case 136: break;
          case 56:
            { return token(sym.FOR, yyline, yycolumn, yytext());
            }
            // fall through
          case 137: break;
          case 57:
            { return token(sym.INT, yyline, yycolumn, yytext());
            }
            // fall through
          case 138: break;
          case 58:
            { return token(sym.BYTE, yyline, yycolumn, yytext());
            }
            // fall through
          case 139: break;
          case 59:
            { return token(sym.CASE, yyline, yycolumn, yytext());
            }
            // fall through
          case 140: break;
          case 60:
            { return token(sym.ELSE, yyline, yycolumn, yytext());
            }
            // fall through
          case 141: break;
          case 61:
            { return token(sym.LONG, yyline, yycolumn, yytext());
            }
            // fall through
          case 142: break;
          case 62:
            { return token(sym.VERDADERO, yyline, yycolumn, yytext());
            }
            // fall through
          case 143: break;
          case 63:
            { return token(sym.BREAK, yyline, yycolumn, yytext());
            }
            // fall through
          case 144: break;
          case 64:
            { return token(sym.CLASS, yyline, yycolumn, yytext());
            }
            // fall through
          case 145: break;
          case 65:
            { return token(sym.FALSO, yyline, yycolumn, yytext());
            }
            // fall through
          case 146: break;
          case 66:
            { return token(sym.FINAL, yyline, yycolumn, yytext());
            }
            // fall through
          case 147: break;
          case 67:
            { return token(sym.FLOAT, yyline, yycolumn, yytext());
            }
            // fall through
          case 148: break;
          case 68:
            { return token(sym.SHORT, yyline, yycolumn, yytext());
            }
            // fall through
          case 149: break;
          case 69:
            { return token(sym.WHILE, yyline, yycolumn, yytext());
            }
            // fall through
          case 150: break;
          case 70:
            { return token(sym.STRING, yyline, yycolumn, yytext());
            }
            // fall through
          case 151: break;
          case 71:
            { return token(sym.DOUBLE, yyline, yycolumn, yytext());
            }
            // fall through
          case 152: break;
          case 72:
            { return token(sym.IMPORT, yyline, yycolumn, yytext());
            }
            // fall through
          case 153: break;
          case 73:
            { return token(sym.PUBLIC, yyline, yycolumn, yytext());
            }
            // fall through
          case 154: break;
          case 74:
            { return token(sym.RETURN, yyline, yycolumn, yytext());
            }
            // fall through
          case 155: break;
          case 75:
            { return token(sym.SWITCH, yyline, yycolumn, yytext());
            }
            // fall through
          case 156: break;
          case 76:
            { return token(sym.BOOLEAN, yyline, yycolumn, yytext());
            }
            // fall through
          case 157: break;
          case 77:
            { return token(sym.DEFAULT, yyline, yycolumn, yytext());
            }
            // fall through
          case 158: break;
          case 78:
            { return token(sym.PACKAGE, yyline, yycolumn, yytext());
            }
            // fall through
          case 159: break;
          case 79:
            { return token(sym.PRIVATE, yyline, yycolumn, yytext());
            }
            // fall through
          case 160: break;
          case 80:
            { return token(sym.CONTINUE, yyline, yycolumn, yytext());
            }
            // fall through
          case 161: break;
          case 81:
            { return token(sym.PROTECTED, yyline, yycolumn, yytext());
            }
            // fall through
          case 162: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
