
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LEFTBRACKET = 10;
  public static final int INTERROGATION = 12;
  public static final int SHORT = 15;
  public static final int CHAR = 16;
  public static final int ASSIGNMENT = 43;
  public static final int STRICTFP = 42;
  public static final int RIGHTBRACKET = 11;
  public static final int DOUBLE = 20;
  public static final int SMALLER = 22;
  public static final int PRIVATE = 35;
  public static final int GREATER = 23;
  public static final int INTERFACE = 31;
  public static final int INT = 17;
  public static final int STATIC = 25;
  public static final int SEMICOLON = 2;
  public static final int COMMA = 5;
  public static final int THROW = 48;
  public static final int CLASS = 27;
  public static final int AMPERSAND = 13;
  public static final int LEFT = 8;
  public static final int ABSTRACT = 36;
  public static final int EOF = 0;
  public static final int BOOLEAN = 21;
  public static final int RIGHTCURLY = 45;
  public static final int TRANSIENT = 40;
  public static final int SUPER = 32;
  public static final int error = 1;
  public static final int VOID = 46;
  public static final int TRIPLEPOINT = 4;
  public static final int LEFTCURLY = 44;
  public static final int BYTE = 14;
  public static final int IMPORT = 26;
  public static final int TIMES = 6;
  public static final int NATIVE = 38;
  public static final int PROTECTED = 34;
  public static final int ENUM = 30;
  public static final int POINT = 3;
  public static final int PACKAGE = 24;
  public static final int FINAL = 37;
  public static final int FLOAT = 19;
  public static final int PUBLIC = 33;
  public static final int EXTENDS = 28;
  public static final int LONG = 18;
  public static final int VOLATILE = 41;
  public static final int THROWS = 49;
  public static final int SYNCHRONIZED = 39;
  public static final int AT = 7;
  public static final int RIGHT = 9;
  public static final int IMPLEMENTS = 29;
  public static final int IDENTIFIER = 47;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMICOLON",
  "POINT",
  "TRIPLEPOINT",
  "COMMA",
  "TIMES",
  "AT",
  "LEFT",
  "RIGHT",
  "LEFTBRACKET",
  "RIGHTBRACKET",
  "INTERROGATION",
  "AMPERSAND",
  "BYTE",
  "SHORT",
  "CHAR",
  "INT",
  "LONG",
  "FLOAT",
  "DOUBLE",
  "BOOLEAN",
  "SMALLER",
  "GREATER",
  "PACKAGE",
  "STATIC",
  "IMPORT",
  "CLASS",
  "EXTENDS",
  "IMPLEMENTS",
  "ENUM",
  "INTERFACE",
  "SUPER",
  "PUBLIC",
  "PROTECTED",
  "PRIVATE",
  "ABSTRACT",
  "FINAL",
  "NATIVE",
  "SYNCHRONIZED",
  "TRANSIENT",
  "VOLATILE",
  "STRICTFP",
  "ASSIGNMENT",
  "LEFTCURLY",
  "RIGHTCURLY",
  "VOID",
  "IDENTIFIER",
  "THROW",
  "THROWS"
  };
}

